### ISSUE TITLE
cryptography dependency

### ISSUE THREAD

**Issue by kukosk** [web-push-libs/pywebpush#105]
Hey there,

I was updating pywebpush on my webserver today, and got into problems with the cryptography package. `pip install -U` didn't update it to the latest version, because it isn't required by the requirements.txt, although the code uses functionality introduced in 2.6 (serialization.Encoding.X962).

I think you should consider bumping up the version of cryptography in the requirements to 2.6.1.

**Comment by jrconlin** [comment]
wfm.

It's been a while since I set the baseline for requirements anyway.

Thanks!

**Comment by jrconlin** [comment]
pushed 1.9.1 https://pypi.org/project/pywebpush/

**Comment by kukosk** [comment]
Wow, that was quick, thank you 👍
