### ISSUE TITLE
aes128gcm stop working

### ISSUE THREAD

**Issue by stalkerg** [web-push-libs/pywebpush#115]
I don't know but aes128gcm stop working. Everything sending fine, but in the browser, I have null instead data. If I am using aesgcm everything fine. In chrome://gcm-internals/ I have no any "errors".

**Comment by jrconlin** [comment]
I am traveling today, so I can't look into this.

It is odd because if the message isn't understood by the browser, the browser will reject it. I am not sure why you are seeing null.

If you can, please let me know:
What browser you're using (firefox, chrome, edge, etc.) and what version. I will try to reproduce and see what's happening.

Thanks!

**Comment by stalkerg** [comment]
> I am traveling today, so I can't look into this.

No problem, until aesgcm working fine, also I have some ideas about how to check it. 
I am using Chromium 74.0.3729.169 but my users started told me about a problem from different browsers. 
If you can't reproduce it, it still can be a problem in my code. 

Thanks!

**Comment by stalkerg** [comment]
I add gcm_key to your main program as an argument and I riched the same result. (without data in browser)
It's working for gcm and fcm endpoints.

**Comment by jrconlin** [comment]
Huh, I'm not able to verify the problem you're seeing. I'm able to test using chrome by 
1) fetching the subscription info off of https://gauntface.github.io/simple-push-demo/
2) copying it into a file like `test/chrome_sub.json`
3) writing some message data to a file  like `data.txt`
4) writing my VAPID claims to `vapid.claims' (Something simple like `{"sub": "mailto:me@example.org"}`)
5) Use a private chrome key stored as URL safe base64 into `test/chrome_priv.raw`
6) calling `pywebpush --encoding aes128gcm --data data.txt --info test/chrome_sub.json --claims vapid.claims --key test/chrome_priv.raw`

This results in me getting a notification from the gauntface.github.io page. 

I'm a bit curious why you're not seeing messages for aes128gcm vs aesgcm. If you're doing something similar to what I am doing, the data should be encoded properly.I wonder if there might be a problem with the Service Worker component. (Probably not, but might be worth checking) I know that with Firefox at least, it's possible to view the Browser Console (Ctrl+Shift+J) which would show if the message was received and if there were any issues with decrypting the body of the message. The good news is that once it works in one browser, it should work in all of them.

I'm a bit stumped as to what might be going on. Sorry.

**Comment by stalkerg** [comment]
I didn't use VAPID... maybe that reason? Anyway, thanks, I will check what did you say.

**Comment by stalkerg** [comment]
I still need to check it but looks like it is https://developers.google.com/web/updates/2016/07/web-push-interop-wins  
I am still using gcm key instead of VAPID.

**Comment by stalkerg** [comment]
Hmmm with VAPID I have 403 Forbidden (and yes, I add ttl)

**Comment by stalkerg** [comment]
ok, I finished figure out, probably it's a bug but not a pywebpush. 
If we are using aes128gcm we MUST use VAPID and use public key during subscribe on the client side. 
Chrome: aes128gcm+gcm_key = wokring but notification without data. 
Firefox: aes128gcm+gcm_key = not working
Chrome: aes128gcm+VAPID without public key on client = 403 Forbidden
Firefox: aes128gcm+VAPID without public key on client = working fine

now I should recreate tokens for all users... hm...

**Comment by jrconlin** [comment]
Sorry, still traveling so could not respond earlier. 

Google is far stricter about requiring VAPID. I am surprised that it worked without VAPID at all. Mozilla doesn't require the header. 

I am not sure what the best way is to update your customers. Hopefully they check your site regularly and you can just update the service worker to reregister.

**Comment by stalkerg** [comment]
> Google is far stricter about requiring VAPID. I am surprised that it worked without VAPID at all. 

With old aesgcm and gcm_key for Chrome all working fine. 
Anyway this situation very confusing.
