### ISSUE TITLE
Push Notification for Chrome

### ISSUE THREAD

**Issue by naveensinghal** [web-push-libs/pywebpush#12]
Hi @jrconlin 

I am trying to send Push Notification to Chrome Browser using Pywebpush Library. But the call seems to be not working.

I am trying the following code: 
```
subscription_info = {'endpoint': endpoint, 'keys': {'p256dh': p256dh_key, 'auth': auth_key}}
notify_data = {"data": "Hello"}
headers = {'Content-Type': 'application/json'}
gcm_key = "AIzaSXXXXXXXXXXXXXXXXXXXXX"
resp = WebPusher(subscription_info).send(notify_data, headers, 3600, gcm_key)
```

And I am getting this as the Error: 
`TypeError: send() takes at most 4 arguments (5 given)`

Can you please suggest how can I use Pywebpush send() to send Push Notification to Chrome Browser ? 

Thanks,

**Comment by safwanrahman** [comment]
Hi @naveensinghal,

If you are using django, you can use ``django-webpush``. It has handeled everything for chrome.
