### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by jensenbox** [web-push-libs/pywebpush#136]
The latest release includes better sub claim validation logic - especially for localhost testing.

Would be great to craft a new release that incorporates it.

Thanks!

https://github.com/web-push-libs/vapid/pull/92/commits/01349c73ced4d7ad8a215c5b2ee83231ec134925#diff-50624f971250f7416e716ae9e116ffe51a709db1e18ad02969e15f0d09143a1bR353

**Comment by jrconlin** [comment]
Crap, I did forget to do that.

Right let me tag a release here, and I'll push it to pypi monday. (I've been a backend guy long enough to know that you NEVER release a library update on Friday or a weekend.)

_goes and adds a calendar reminder..._

**Comment by jensenbox** [comment]
ping :)

**Comment by jrconlin** [comment]
Hrm. so 1.13.0 got pushed Mar. 16.
There's been no changes since then, so it's up to date.

**Comment by jensenbox** [comment]
Is this getting in there? https://pypi.org/project/py-vapid/1.8.1/

**Comment by jrconlin** [comment]
So, `[requirements.txt](https://github.com/web-push-libs/pywebpush/blob/main/requirements.txt)` lists minimum versions for libraries, so yes. 

existing installs can use `pip3 install --upgrade -r requirements.txt` to update current libraries.
