### ISSUE TITLE
Is the library being maintained

### ISSUE THREAD

**Issue by Shahin-rmz** [web-push-libs/pywebpush#153]
Hello,
The library seems to have very important function (namely web push) but didn't have any updates since 2021. Is Lib being maintained any more?
Thanks

**Comment by jrconlin** [comment]
Yes, it is, although it's been delightfully stable for quite some time, and I sometimes need to get someone to review stuff. Anything critical would get my attention far faster than some of the other things on the list.

I generally review and update things if needed every three months or so.
