### ISSUE TITLE
pywebpush on pypi / git releases

### ISSUE THREAD

**Issue by jleclanche** [web-push-libs/pywebpush#16]
This package is on pypi:
https://pypi.python.org/pypi/pywebpush/

It's unclear whether that's an official package, seeing as there are no git-tagged releases and README.md does not mention it. If it is an official package, I would suggest doing both of those.

Edit: As a sidenote, [this repo](https://github.com/jrconlin/pywebpush) should really be deleted or turned into just a README.

**Comment by jrconlin** [comment]
I'll admit that I've been slacking on tagging. I've fixed that. 

Not quite sure I follow by what you mean as "official". This is a library, potentially one of many, possibly better ones. It fills a current gap that no one has put out a library that shows how to take subscription data, encode it and deliver it to the Push Server. I'd say that this is no more an official library than there's an official HTTP/2 library. 

Am I misunderstanding?

**Comment by jleclanche** [comment]
What I meant is, if that pypi repo is yours, you should link to it in the readme :)

**Comment by jrconlin** [comment]
Ah, heh, yeah, that would probably be useful.

**Comment by jrconlin** [comment]
Closed: https://github.com/web-push-libs/pywebpush/pull/17
