### ISSUE TITLE
For edge, I only get 400 Bad Request. I tested it in webpush library for node. It works properly.

### ISSUE THREAD

**Issue by quroom** [web-push-libs/pywebpush#161]
```
With pywebpush latest.
try:
    webpush(
        subscription_info={
            "endpoint": "https://wns2-pn1p.notify.windows.com/w/?token=BQYAAACFux1wyiPSDqVcMvnBRnb7Vg6NMdGRcmgJV6TDobZLzVvNFTogkgie6lSlOPAdGmtC10lpmcchVdIL8%2bll6FtsYOP9kA4M1CUZKB668YdgmIcg4FnHh4IWFOj5WHSGLLhhNuJw40%2f7TzpnDEJ2mH78dCBWwXYPTWoTRoYEVcqw6QjDYsLHojWHceVcWOHqokVLqDKBOhBGevirxY0ZthCJz91O9tTsE3gpCE%2bdrf9qhK%2bPJitGF0J6EM4h6xeSzERm6Qg3vZDTKmoNXM3RymJR5dUIZGWLKfbEWDJTncCjd8bibd7Lqg%2b0oqjdxYKQF8Q%3d",
            "keys": {
                "p256dh": "BNv-kpItGLybLtcl-RbVZKK5YrCwgJNMjLo9drzS6jCVm-YXMW21mQ5DK1pPrWPQG2cTKJH0QTXFc5IdfcD_Br8",
                "auth": "4PPU40n9wOfZqOKEDjD8KA"
            }},
        data="Mary had a little lamb, with a nice mint jelly",
        vapid_private_key="TqoRbiCxPrbbkU8HMacQ111-Yx3sNvy84Q_5ooJf5rY",
        vapid_claims={
                "sub": "mailto:YourNameHere@example.org",
            }
    )
except WebPushException as ex:
    print("I'm sorry, Dave, but I can't do that: {}", repr(ex))
    # Mozilla returns additional information in the body of the response.
    if ex.response and ex.response.json():
        extra = ex.response.json()
        print("Remote service replied with a {}:{}, {}",
              extra.code,
              extra.errno,
              extra.message
              )
```
I get only this response `I'm sorry, Dave, but I can't do that: {} WebPushException('Push failed: 400 Bad Request')`

```
With node webpush module.
  web-push send-notification  \
  --endpoint=https://wns2-pn1p.notify.windows.com/w/?token=BQYAAACFux1wyiPSDqVcMvnBRnb7Vg6NMdGRcmgJV6TDobZLzVvNFTogkgie6lSlOPAdGmtC10lpmcchVdIL8%2bll6FtsYOP9kA4M1CUZKB668YdgmIcg4FnHh4IWFOj5WHSGLLhhNuJw40%2f7TzpnDEJ2mH78dCBWwXYPTWoTRoYEVcqw6QjDYsLHojWHceVcWOHqokVLqDKBOhBGevirxY0ZthCJz91O9tTsE3gpCE%2bdrf9qhK%2bPJitGF0J6EM4h6xeSzERm6Qg3vZDTKmoNXM3RymJR5dUIZGWLKfbEWDJTncCjd8bibd7Lqg%2b0oqjdxYKQF8Q%3d  \
  --key=BNv-kpItGLybLtcl-RbVZKK5YrCwgJNMjLo9drzS6jCVm-YXMW21mQ5DK1pPrWPQG2cTKJH0QTXFc5IdfcD_Br8 \
  --auth=4PPU40n9wOfZqOKEDjD8KA \
  --vapid-subject=mailto:example@qq.com \
  --vapid-pubkey=BCNpfCmfaTVb_dsgucwqJXleQpk4b0xjHJFZnodrdofHcdh4UoEcWuRCVdvpoMKaIifxvlVPi2fpIWpuauZFXC0 \
  --vapid-pvtkey=TqoRbiCxPrbbkU8HMacQ111-Yx3sNvy84Q_5ooJf5rY \
  --payload=Hello
```

It works well same parameter in webpush node module.
I don't know why it doesn't work well.
Could you help me?

**Comment by quroom** [comment]
I am not sure what the problem was exactly. But now it works.
I only changed urlBase64ToUint8Array function
`const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");`
to
```
const base64 = (base64String + padding)
    // eslint-disable-next-line no-useless-escape
    .replace(/\-/g, "+")
    .replace(/_/g, "/");

```

I don't think it is related.
As long as I figure out it, I will leave some comment.

**Comment by quroom** [comment]
It's because of ttl I didn't write.

**Comment by jrconlin** [comment]
Yep, the `TTL` is required (according to [the RFC](https://www.rfc-editor.org/rfc/rfc8030#section-5.2)) I'll also caution about using standard base64 encoding. Python is very lax about what it accepts, but other languages (like Rust) are exceptionally pedantic about things. 

`send()` _should_ set `ttl` to 0 [if you don't supply one](https://github.com/web-push-libs/pywebpush/blob/7bb3b19993d9886940dc2b28c731c0c86dab700c/pywebpush/__init__.py#L360). If it's not doing that, it might be a legit bug.

**Comment by quroom** [comment]
> Yep, the `TTL` is required (according to [the RFC](https://www.rfc-editor.org/rfc/rfc8030#section-5.2)) I'll also caution about using standard base64 encoding. Python is very lax about what it accepts, but other languages (like Rust) are exceptionally pedantic about things.
> 
> `send()` _should_ set `ttl` to 0 [if you don't supply one](https://github.com/web-push-libs/pywebpush/blob/7bb3b19993d9886940dc2b28c731c0c86dab700c/pywebpush/__init__.py#L360). If it's not doing that, it might be a legit bug.

Then I guess it should be set with default value or showing error for like "need to set TTL"
Because without setting it, almost every browser works , but edge doesn't work and response 400 error not including much information.

**Comment by vikas08-nagarro** [comment]
Just add following and get your issue sorted :

webpush(
                subscription_info=subscription_info,
                data=json.dumps(message),
                vapid_private_key=self.vapid_private_key,
                vapid_claims=vapid_claims,
                **headers={'TTL': '3600'}**
            )
