### ISSUE TITLE
Requests requirement.

### ISSUE THREAD

**Issue by balloob** [web-push-libs/pywebpush#18]
Requests is a popular requirement. By pinning the version you require all other packages that want to depend on you to use the same version. Could the requirement be made more flexible?

And now as a counter argument to this request, pywebpush currently does not work with Requests 2.11.0 due to [the following change](https://github.com/kennethreitz/requests/blob/master/HISTORY.rst#2110-2016-08-08):

> Some previous releases accidentally accepted non-strings as acceptable header values. This release does not.

This breaks as `ttl` header defaults to the integer `0`.

**Comment by jrconlin** [comment]
Yeah, for production level releases, it's always good to be very definitive about what versions of libraries you work with, mostly to counter stuff like this. I should refresh the baseline and patch up. I believe there's a plug-in that will report out-of-date requirements. I'll see about adding it.

**Comment by jrconlin** [comment]
blocked: Waiting for auth for circleci and requires.io.
