### ISSUE TITLE
pywebpush Issue

### ISSUE THREAD

**Issue by naveensinghal** [web-push-libs/pywebpush#20]
Hi @jrconlin 

I am trying to use PyWebpush Library in my python code and I am seeing these 3 kind of issues on the server side logs for chrome notifications(working absolutely fine in all cases on local server):
1) `ConnectionError(ProtocolError('Connection aborted.', error(0, 'Error')),)`
2) `'[OpenSSL] EC_KEY_generate_key FAIL ... error:00000000:lib(0):func(0):reason(0)',)`
[Occurs for this line:
encoded = WebPusher(subscription_info).encode(json.dumps(data))]
3) `extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter. Returning 0.`

Can you please suggest how can these issues be resolved ?

Thanks,

**Comment by jrconlin** [comment]
Huh, I've not seen that error before. Could you tell me a bit more about:
What version of python are you running (pypy, cpython, jython, etc. and what actual version number)?
What OS your running on?

Looking at the content of the error, it looks like there's something up with the OpenSSL crypto library. Specifically, the Elliptical Curve (EC_KEY) functions may not be available. That can be a problem for some platforms like Android, which ships a stripped down OpenSSL implementation that doesn't have EC support. 

It also looks like there may be a problem with the ffi library. It may be that you need to hand build those libraries, which would not be fun.

**Comment by naveensinghal** [comment]
I am using Python Version: 2.7.9 on Ubuntu 15.04.

requirements.txt: (partial)
cffi==1.7.0
http-ece==0.5.0
cryptography==1.4
pycparser==2.14
pycrypto==2.6.1
pyelliptic==1.5.7
pyOpenSSL==16.0.0
pyasn1==0.1.9
pyasn1-modules==0.0.8
python-jose==0.5.6
pytz==2016.6.1
simplejson==3.8.2
six==1.10.0
uritemplate==0.6
urllib3==1.16

Not sure if it helps but i don't have cpython, jython(or jpython) etc. in my requirements.txt file

I am using it only for Web Push Notifications. The behavior is only intermittent on server side. It does works sometimes. On local server, it works all the times without any error.

**Comment by naveensinghal** [comment]
@jrconlin , Can you please suggest few steps/solution to resolve this ?

**Comment by jrconlin** [comment]
I'm not sure I can help solve this, or at least provide an easy solution. Your python libs match the requirements spec, so in theory, that part should work fine. The problem, though, isn't with the python parts, it's with the libraries that those python parts are calling out to. I'm not sure why, but those are failing. Looking at the error you provided, i'd probably work backwards from the libffi  (for what it's worth: I've got  "3.1+") and then maybe look at what version of OpenSSL ("1.0.1+")

The error you're noting happens far lower than my code, so I'm not quite sure what the full cause is. Honestly, if you figure it out, I'd love to know what the solution might be.

**Comment by jrconlin** [comment]
I'm not sure I can help solve this, or at least provide an easy solution. Your python libs match the requirements spec, so in theory, that part should work fine. The problem, though, isn't with the python parts, it's with the libraries that those python parts are calling out to. I'm not sure why, but those are failing. Looking at the error you provided, i'd probably work backwards from the libffi  (for what it's worth: I've got  "3.1+") and then maybe look at what version of OpenSSL ("1.0.1+")

The error you're noting happens far lower than my code, so I'm not quite sure what the full cause is. Honestly, if you figure it out, I'd love to know what the solution might be.
