### ISSUE TITLE
AttributeError: 'X509' object has no attribute '_x509'

### ISSUE THREAD

**Issue by mallik482** [web-push-libs/pywebpush#31]
![screen shot 2016-12-15 at 3 42 12 pm](https://cloud.githubusercontent.com/assets/12051878/21220055/33610dda-c2dd-11e6-8b83-5fb8f37ea9c1.png)
I have installed pywebpush globally. My code is below config.py
from pywebpush import WebPusher

    subscription_info = {"endpoint":"https://android.googleapis.com/gcm/send/e8N4w87NpOE:APA91bFmYdTBaeROOmBbzKoHD6X6QsQfJEA_Jvrzbsgc0gm-6eKlJOb20H0CQ47v6_CLIXPstre6r-7X06ea_Vm_EtTkGMKAc_e2tBN7WhaiNzhspuKcr1IHKz6ucyxe8FWrvRXyFWwr","keys":{"p256dh":"BE0i3dGxDr4aJ0ACZ-JQtcPieaXZaAS1eYqRHP4kJKGzxNe8SEd8En_JtyY7ZEB8COPVUD4wM4AAzuGS7GZBvPY=","auth":"7Gg9jurx6AUPAwD3hA0ZwQ=="}}
    data = "{test:'hello'}"
    headers = {'Authorization' : 'key=firebase_server_key'}
    gcm = 'firebase_server_key'
    wp = WebPusher(subscription_info)
    wp.send(data, headers,ttl=0,gcm_key=gcm)

my python version 2.7.10

When I tried to run the above code giving error

**Comment by jrconlin** [comment]
Looks like this may be an issue inside of the pyopenssl library for your install. You may want to either check to see if it's updated or build and install a local copy. 

Sadly, this isn't a pywebpush error directly, so I can't really help much more than that.
