### ISSUE TITLE
As of today , can we do push notifications without thirdparty?

### ISSUE THREAD

**Issue by v3ss0n** [web-push-libs/pywebpush#32]
Is that possible to do push notifications in serviceworker without depending on thirdparty like 
GCM or mozilla push services? 
Is that possible to have our own push servers?

**Comment by jrconlin** [comment]
I think the best answer is: "It depends"

If you want to have private versions of firefox for desktop connect to your private server, then yes, it's possible. Firefox for Android currently relies on GCM for a number of reasons (battery life, OS level privileges, etc.) so it's not easy to switch that over. 

As I understand your core problem, network connectivity is not very reliable at your location, and you wish to have sub-second, continuous updates. There are other tools that exist which might aid you (XMPP / Jabber, WebRPC, etc.) however all of these have significant limitations as well  (XMPP requires your device CPU to stay active and not sleep, WebRPC requires a live connection between to machines, etc.)

It may be that the best solution to messaging across slow or unreliable networks is to use email and polling. It's not going to be immediate, but may offer the best compromise.

**Comment by v3ss0n** [comment]
Thank you very much for this explanation!
