### ISSUE TITLE
Handle an empty payload

### ISSUE THREAD

**Issue by Natim** [web-push-libs/pywebpush#40]
Webpush supports sending empty payloads.
For most use case we have with Kinto it makes sense to just try to resync on push notifications and not worry about any payload.

It would be nice for pywebpush to handle `send(data=None )`

**Comment by jrconlin** [comment]
hrm. My first thought was that if you don't have data, don't even bother calling the library. It's heavier weight than you probably need or want. 

I can see some value for having no data. but I'll probably just call out to requests with no additional processing.
