### ISSUE TITLE
http_ece 0.7.1 import error cause by pyelliptic is deprecated

### ISSUE THREAD

**Issue by doandu** [web-push-libs/pywebpush#48]
I'm facing with error happens when import this library caused by the dependency 'http_ece' 0.7.1 uses the deprecated 'pyelliptic'. It seems this fixed in 'http_ece' 0.7.3
Please check [here](https://github.com/martinthomson/encrypted-content-encoding/issues/33) for  more details.
Thank you very much.

**Comment by doandu** [comment]
@jrconlin thank you very much for your support.

**Comment by jrconlin** [comment]
I'm working on a significant refactor to use python's cryptography library to speed things up and remove similar deprecated libraries. I'll update this to use http_ece 0.7.3 as part of that.

**Comment by Flimm** [comment]
[http_ece 1.0](https://pypi.python.org/pypi/http-ece) has been released, which no longer depends on pyelliptic. Could the requirements of `pywebpush` be updated to reflect that?

**Comment by jrconlin** [comment]
OBE by #53 (Thanks!)
