### ISSUE TITLE
Depend on any version of `requests`

### ISSUE THREAD

**Issue by Flimm** [web-push-libs/pywebpush#56]
Is there a reason that `pywebpush` depends on specific version of `requests`?

When I run `pip check` after upgrading `requests`, I get this error:

```
$ pip check
pywebpush 1.0.2 has requirement requests==2.13.0, but you have requests 2.14.2.
```

Is there a reason that `install_requires` in `setup.py` pins the dependencies to certain version numbers? (Related: [install_requires vs Requirements files](https://packaging.python.org/requirements/))

**Comment by jrconlin** [comment]
For stability reasons, it's always a good idea to "vendor lock" a library. I know that pywebpush works correctly with requests 2.13.0, but have not tested against 2.14.2 yet. Unfortunately, a number of libraries can and have introduce breaking changes. 

That said, it's my responsibility to update libraries regularly and re-release,
