### ISSUE TITLE
Issues with cryptography==1.8.2 

### ISSUE THREAD

**Issue by trunet** [web-push-libs/pywebpush#58]
cryptography 1.8.2 will not compile with libressl because of some bugs that was fixed on 1.9.0. Is it possible to change requirements.txt to use cryptography>=1.8.2 so the latest will be used?

**Comment by kitcambridge** [comment]
See #57. 😄 Does pywebpush 1.0.4 work for you?

**Comment by kitcambridge** [comment]
Sorry, I misunderstood that 1.8.2 *doesn't* work. Ignore me.

**Comment by jrconlin** [comment]
Looks like there may be a problem with cryptography 1.9. Will investigate and update.

**Comment by jrconlin** [comment]
Ok, well, awesome.

Cryptography has apparently changed [how it returns](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#cryptography.hazmat.primitives.asymmetric.ec.ECDSA) a signature verification. Previously the function would return `False`. Now it throws an exception. Easy to handle, but kinda underscores why I tend to version lock to an explicit version.

**Comment by trunet** [comment]
is it ok to ask you to bump the version 😄 ?

**Comment by jrconlin** [comment]
The latest version of pywebpush (1.0.5) accepts all between 1.8.1 and 1.10. Unfortunately, there's a dependent library that may require the older version. The version has been patched, but I have no idea when the author will release an update to pypi.
