### ISSUE TITLE
Data only sends "title"

### ISSUE THREAD

**Issue by mwent-cray** [web-push-libs/pywebpush#61]
I am trying to send this block as notification:

```
{
"title": "Hello",
"body": "World",
"renotify": true
}
```

But it gets compiled into:
`{"notification":{"title":"{'renotify': True, 'title': 'Hello', 'body': 'World'}"}}`

Please advise

**Comment by jrconlin** [comment]
I'll admit that I'm a bit confused by this one. I take the data verbatim and encode it. It might help to know a bit more.
Are you sending to Chrome or Firefox?
Are you sending to a mobile or desktop browser?
Have you tried a page like https://gauntface.github.io/simple-push-demo/ to see if you get the same result? 
Are you handling the javascript `push` event directly or is there a wrapper framework involved?

**Comment by mwent-cray** [comment]
Ran the python backend on a Macbook as well as 2 unix machined (same results)
Tried chrome (desktop & mobile) and firefox

Frontend I'm running Angular 4 with the NgServiceWorker as well as plain JS
I'm having issues properly capturing push events as well :/ 

Rather annoying issues

**Comment by mwent-cray** [comment]
Any clue how to proceed, any tests and examples the data is of string format.
But say I want to send a options along with the title (defined here: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification)

**Comment by mwent-cray** [comment]
Ok I found the solution - maybe a good idea to implement into the readme?

replace
`data = "Mary had a little sheep`
with
```
data = json.dumps({
        "notification": {
        "title": "Mary had a little lamb",
        "body": "with some nice mint jelly"
        # All other options here as well
    }})
```
