### ISSUE TITLE
Documentation on how to use?

### ISSUE THREAD

**Issue by ChangezKhan** [web-push-libs/pywebpush#67]
Any kind of documentation is available on how to use this library?

**Comment by jrconlin** [comment]
Well, the README has a few examples, more for general, casual use, like one step calling with the `webpush` convenience function or initializing the `WebPusher` object and calling the `.send()` method. 

What sort of things are you looking to do?

**Comment by ChangezKhan** [comment]
Ok, I got it. At first I got confused with `README` file. But later, checked once more, and now able to understand it.

**Comment by jrconlin** [comment]
Cool. I'd love any advice you might have to clear up whatever confusion you had. (Short of "Good coffee before helps". I've so been there.)
