### ISSUE TITLE
Not able to install pywebpush

### ISSUE THREAD

**Issue by ChangezKhan** [web-push-libs/pywebpush#68]
Hello all, I am trying to install `pywebpush` using `pip install pywebpush` but I am unable to do so. I am getting following error.

```
kapil@sohan:~/Projects/pywebpush$ pip install pywebpush
Downloading/unpacking pywebpush
  Downloading pywebpush-1.0.5.tar.gz
  Running setup.py (path:/tmp/pip_build_kapil/pywebpush/setup.py) egg_info for package pywebpush
    
Downloading/unpacking cryptography>=1.8.1,<1.10 (from pywebpush)
  Downloading cryptography-1.9.tar.gz (409kB): 409kB downloaded
  Running setup.py (path:/tmp/pip_build_kapil/cryptography/setup.py) egg_info for package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking http-ece>=1.0.1 (from pywebpush)
  Downloading http_ece-1.0.2.tar.gz
  Running setup.py (path:/tmp/pip_build_kapil/http-ece/setup.py) egg_info for package http-ece
    error in http_ece setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in http_ece setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_kapil/http-ece
Storing debug log for failure in /tmp/tmpaWU6LN

```

And complete log file is [error.log](https://gist.github.com/ChangezKhan/b186ed3d92b69bfc575257379115ddf3)

And if I try to install it as it said in the `README` file I get this [error](https://gist.github.com/ChangezKhan/cf8468f791dadae90840c725448886ef)

I am unable to install it by any way.

**Comment by martinthomson** [comment]
This might be a problem with a local openssl installation.

See https://github.com/web-push-libs/encrypted-content-encoding/issues/40#issuecomment-310425265

**Comment by ChangezKhan** [comment]
Actually I already have installed `openssl` on my system and it is already newest version. (1.0.2g-1ubuntu4.8). I don't know, what's happening here. I think will need more time to debug and solve the issue. Meanwhile, @martinthomson can you make vagrant file or something? It is happening only when I try to install `cryptography` package.

**Comment by narnikgamarnikus** [comment]
Here https://github.com/yann2192/pyelliptic/issues/50 indicates that you no longer need to use `pyelliptic`, but instead it is better to use https://github.com/pyca/cryptography

**Comment by jrconlin** [comment]
Closing issue since it's not directly related to pywebpush
