### ISSUE TITLE
'unicode' object has no attribute 'get'

### ISSUE THREAD

**Issue by rishabhnag1** [web-push-libs/pywebpush#70]
Hey there, I'm trying to make a webpush call, but its giving me the error:
`'unicode' object has no attribute 'get'`
It looks like that error is being triggered by 
` url = urlparse(subscription_info.get('endpoint'))`'
Any idea what might be causing this?

**Comment by jrconlin** [comment]
off hand, I'd suspect that you're passing a string value for subscription info rather than a dict. 
`subscription_info` is a JSON blob, but it needs to be converted to a python `dict` object before it's useful. `webpush` [does this for you](https://github.com/web-push-libs/pywebpush/blob/master/pywebpush/__main__.py#L26). If you're using the library form, you should probably call `json.loads(subscription_info)`.

**Comment by rishabhnag1** [comment]
yeah, that fixed it, thanks! as a side note the call is now returning Error 400, Unauthorized Registration. Was wondering if you've seen that come up before, or have an idea as to what it might be caused by

**Comment by jrconlin** [comment]
All kinds of things, unfortunately. 

Things to check:
1) You're using the matching private key for the public key you used to register the endpoint.
2) your "sub" is a proper "mailto:name@domain" url specifier. (e.g. "mailto:bob@example.com")
3) if you've specified an "exp" that it's no more than now+ 24 hours and that your server's clock is reasonably accurate.

Firefox's server is a good deal more informative about the type of thing that may have gone wrong, so it' might be worth trying using [Developer Edition ](https://www.mozilla.org/en-US/firefox/developer/) and seeing what the `curl` response says.

https://blog.mozilla.org/services/2016/04/04/using-vapid-with-webpush/ goes into probably inordinate detail about VAPID headers, if it might help.

**Comment by rishabhnag1** [comment]
hey it looks like fixing #1 did the trick! I am getting an OpenSSL error after that point though:

`Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it. ([_OpenSSLErrorWithText(code=50905205L, lib=3, func=140, reason=117, reason_text='error:0308C075:bignum routines:BN_generate_dsa_nonce:private key too large'), _OpenSSLErrorWithText(code=269451422L, lib=16, func=248, reason=158, reason_text='error:100F809E:elliptic curve routines:ECDSA_sign_setup:random number generation failed'), _OpenSSLErrorWithText(code=269455402L, lib=16, func=249, reason=42, reason_text='error:100F902A:elliptic curve routines:ossl_ecdsa_sign_sig:ECDSA lib')])`

Any idea how I'd go about getting around this? The error message isn't very descriptive
