### ISSUE TITLE
Default expiry of 24h may lead to errors

### ISSUE THREAD

**Issue by drott** [web-push-libs/pywebpush#74]
In my experience, the default expiry of 24hours might be causing errors on the push backends of Google and Mozilla. They reject the request, with Mozilla reporting that the expiry is too far in the future, probably due to slight clock differences.

I would suggest to reduce the default expiry time in order to avoid such problems.

**Comment by jrconlin** [comment]
I'm guessing this is more a Vapid error than a pywebpush error. 

Clock skew is always a problem, and the obvious work-around is to specify an `exp` yourself. 

I'll consider reducing the default period to 12 hours, and file the bug on the py-vapid library.

**Comment by drott** [comment]
Thanks, yes, let's move it to: https://github.com/web-push-libs/vapid/issues/56
