### ISSUE TITLE
Support cryptography 2.0

### ISSUE THREAD

**Issue by Flimm** [web-push-libs/pywebpush#75]
Python pywebpush requires cryptography < 1.10, but cryptography 2.0 (up to 2.0.3) has been released. Here are the changes:

https://github.com/pyca/cryptography/blob/master/README.rst

**Comment by jrconlin** [comment]
Updated py_vapid too. Will push this out monday.

**Comment by jrconlin** [comment]
Requires: 
- [ ] https://github.com/web-push-libs/encrypted-content-encoding/pull/44
- [x] https://github.com/web-push-libs/vapid/pull/58

**Comment by jrconlin** [comment]
Sorry that this took a bit longer than I wanted. Did discover a couple of interaction issues with vapid that I cleared up.

**Comment by Flimm** [comment]
Thank you so much!
