### ISSUE TITLE
webpush modifies the vapid_claims parameter

### ISSUE THREAD

**Issue by nglgzz** [web-push-libs/pywebpush#79]
I have an object in my Django config for vapid claims and I'm using it in the webpush method. 

I couldn't realize why after sending push messages on Firefox I was constantly getting "unauthorized registration" errors on Chrome, until I saw that the object passed as `vapid_claims` parameter gets modified from something like this:

```
{
    'sub': 'mailto:<my_email>'
}
```

to this :
```
{
    'aud': 'https://updates.push.services.mozilla.com',
    'exp': '1508309139',
    'sub': 'mailto:<my_email>'
}
```
I tried passing every time a new object and everything works fine, but now I'm wondering, is this expected behavior, and am I supposed to store that modified object?

**Comment by nglgzz** [comment]
Okay, thank you for the clarification 👍

**Comment by cauethenorio** [comment]
@jrconlin thanks man
