### ISSUE TITLE
How to get Response on WebPushException

### ISSUE THREAD

**Issue by SohnyBohny** [web-push-libs/pywebpush#90]
Is there any way to get the HTTP response code / or the response object on WebPushException.

Mozilla for example [sends a 410 code](http://autopush.readthedocs.io/en/latest/http.html#error-codes) when the subscription isn't valid anymore.
In this case I want to delete the subscription from my list.

`raise WebPushException("Push failed: {}: {}".format(
            result, result.text))`

You format the result to string which of course could be parsed. I wonder if there is a better solution.

**Comment by jrconlin** [comment]
Yeah, that's me being lazy. You're right, WebPushException should return the body of the response if it's available. I'll patch that up.

Thank you for keeping me honest (and less lazy).
